//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infra.School.Data.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Assigment
    {
        public int id { get; set; }
        public string enrollmentCode { get; set; }
        public Nullable<int> classid { get; set; }
        public Nullable<int> sectionId { get; set; }
        public Nullable<int> subjectId { get; set; }
        public Nullable<int> uploadedby { get; set; }
        public Nullable<System.DateTime> deadlineDate { get; set; }
        public Nullable<System.DateTime> uploadeOn { get; set; }
        public string filepath { get; set; }
        public string fileName { get; set; }
        public System.Guid UniqueId { get; set; }
        public string AssID { get; set; }
        public string Remark { get; set; }
        public Nullable<bool> uploadstatus { get; set; }
    }
}
