//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infra.School.Data.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attendance
    {
        public int id { get; set; }
        public string EnrollmentCode { get; set; }
        public Nullable<int> attendanceId { get; set; }
        public Nullable<System.DateTime> punchdate { get; set; }
        public Nullable<int> markedby { get; set; }
    }
}
