//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infra.School.Data.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class PassRecovery
    {
        public int id { get; set; }
        public string userid { get; set; }
        public string token { get; set; }
        public Nullable<System.DateTime> createdOn { get; set; }
        public Nullable<System.DateTime> expiryDate { get; set; }
        public Nullable<bool> isExpire { get; set; }
        public Nullable<bool> isReset { get; set; }
    }
}
