//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infra.School.Data.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResultDetail
    {
        public int id { get; set; }
        public int AdmissionID { get; set; }
        public int SubId { get; set; }
        public int SessionId { get; set; }
        public int ResultId { get; set; }
        public string EvaluationMarks { get; set; }
        public int IsEvaluteType { get; set; }
    }
}
