//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infra.School.Data.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class SessionMaster
    {
        public int id { get; set; }
        public Nullable<int> starthrs { get; set; }
        public Nullable<int> startmin { get; set; }
        public Nullable<int> endHrs { get; set; }
        public Nullable<int> endMin { get; set; }
        public string startTimeformate { get; set; }
        public string EndTimeformate { get; set; }
        public string sessionYear { get; set; }
        public Nullable<int> Years { get; set; }
        public Nullable<int> Months { get; set; }
        public Nullable<int> EndMonths { get; set; }
    }
}
