//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infra.School.Data.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int Id { get; set; }
        public string admissionId { get; set; }
        public string firstname { get; set; }
        public string lastName { get; set; }
        public string gender { get; set; }
        public string fathername { get; set; }
        public string motherName { get; set; }
        public Nullable<int> classId { get; set; }
        public Nullable<int> sectionId { get; set; }
        public string rollNo { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public System.Guid UniqueId { get; set; }
        public string Address1 { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
    }
}
