//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infra.School.Data.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeacherDetail
    {
        public int id { get; set; }
        public string enrollmentCode { get; set; }
        public string firstName { get; set; }
        public string midName { get; set; }
        public string Lastname { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Phone { get; set; }
        public string Dob { get; set; }
        public string Doj { get; set; }
        public string DateOfexit { get; set; }
        public string Email { get; set; }
        public System.Guid UniqueId { get; set; }
    }
}
