//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infra.School.Data.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int id { get; set; }
        public string userId { get; set; }
        public byte[] PasswordHash { get; set; }
        public byte[] PasswordSalt { get; set; }
        public Nullable<System.DateTime> createOn { get; set; }
        public Nullable<System.DateTime> lastLogin { get; set; }
        public Nullable<int> numberOfFiledLogin { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<bool> isDelete { get; set; }
        public string createBy { get; set; }
        public string PhoneNo { get; set; }
        public string EmailId { get; set; }
        public System.Guid UniqueId { get; set; }
    }
}
